name: Setup Node.js

on: [push]

env:
  NODE_VERSION: $(jq -r .volta.node package.json)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print node version
        run: "echo node version: ${{ env.NODE_VERSION }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
